;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        comment-line
        electric-pair-delete-pair
        end-of-visual-line
        eval-last-sexp
        indent-for-tab-command
        kill-region
        multiple-cursors-mode
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-cycle
        org-delete-char
        org-end-of-line
        org-kill-line
        org-meta-return
        org-metaleft
        org-metaright
        org-open-line
        org-self-insert-command
        org-shiftleft
        org-shiftright
        org-yank
        paredit-semicolon
        query-replace
        tab-next
        text-scale-increase
        xah-toggle-letter-case
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        ignore
        org-mouse-down-mouse
        org-return-and-maybe-indent
        org-time-stamp-inactive
        text-scale-decrease
        wdired--self-insert
        ))
